#!/bin/bash

set -e

rm_ldconfig() {
    rm -f /etc/ld.so.conf.d/libhsa-rocprofiler64.conf && ldconfig
}

case "$1" in
   remove)
       rm_ldconfig
   ;;
   purge)
   ;;
   *)
       exit 0
   ;;
esac
